version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mam-app:
    build: ./
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
      - ${TCP_PORT}:${TCP_PORT}
    volumes:
      - ${LOG_FILES_VOLUME_PATH}:/app/logFiles

volumes:
  mongodb_data:
  mongodb_config:
